
services:
  app:
    image: assassincreed2k1/hanaya-shop:latest
    container_name: hanaya-shop-app
    ports:
      - "80:80"
    # Environment variables for the application. You can fill values here or mount from a .env file.
    # APP_ENV: Application environment (production/development)
    # APP_DEBUG: Enable/disable debug mode (true/false)
    # APP_URL: Application URL
    # DB_HOST: Database service name, use 'db' if running with Docker Compose
    # DB_DATABASE: Database name, e.g. hanaya_shop
    # DB_USERNAME: Database username
    # DB_PASSWORD: Database password
    # REDIS_HOST: Redis service name, use 'redis' if running with Docker Compose
    # CACHE_DRIVER: Cache driver (e.g. redis)
    # SESSION_DRIVER: Session driver (e.g. redis)
    # QUEUE_CONNECTION: Queue driver (e.g. redis)
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_URL=http://localhost
      - DB_HOST=db
      - DB_DATABASE=
      - DB_USERNAME=
      - DB_PASSWORD=
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    volumes:
      - storage_data:/var/www/html/storage/app
      - logs_data:/var/www/html/storage/logs
      - images_data:/var/www/html/public/images
    depends_on:
      - db
      - redis
    networks:
      - hanaya-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  db:
    image: mysql:8.0
    container_name: hanaya-shop-db
    # MySQL environment variables. Fill values here or mount from a .env file.
    # MYSQL_ROOT_PASSWORD: MySQL root password (only for initial setup)
    # MYSQL_DATABASE: Database name
    # MYSQL_USER: Database username
    # MYSQL_PASSWORD: Database password
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hanaya-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  redis:
    image: redis:7-alpine
    container_name: hanaya-shop-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - hanaya-network
    restart: unless-stopped
    command: redis-server --appendonly yes

volumes:
  db_data:
    driver: local
  redis_data:
    driver: local
  storage_data:
    driver: local
  logs_data:
    driver: local
  images_data:
    driver: local

networks:
  hanaya-network:
    driver: bridge
