name: Debug Workflow

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Debug Info
        run: |
          echo "Workflow is running successfully!"
          echo "Branch: ${{ github.ref }}"
          echo "Commit: ${{ github.sha }}"
          echo "Repository: ${{ github.repository }}"
          
      - name: Check Secrets
        run: |
          echo "Checking secrets availability..."
          if [ -z "${{ secrets.DOCKERHUB_USERNAME }}" ]; then
            echo "❌ DOCKERHUB_USERNAME secret is missing"
          else
            echo "✅ DOCKERHUB_USERNAME secret is available"
          fi
          
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "❌ DOCKERHUB_TOKEN secret is missing"
          else
            echo "✅ DOCKERHUB_TOKEN secret is available"
          fi
          
          if [ -z "${{ secrets.PRODUCTION_SSH_KEY }}" ]; then
            echo "❌ PRODUCTION_SSH_KEY secret is missing"
          else
            echo "✅ PRODUCTION_SSH_KEY secret is available"
          fi
          
          if [ -z "${{ secrets.PRODUCTION_HOST }}" ]; then
            echo "❌ PRODUCTION_HOST secret is missing"
          else
            echo "✅ PRODUCTION_HOST secret is available"
          fi
          
          if [ -z "${{ secrets.PRODUCTION_USER }}" ]; then
            echo "❌ PRODUCTION_USER secret is missing"
          else
            echo "✅ PRODUCTION_USER secret is available"
          fi