name: Staging Deploy

on:
  push:
    branches: [develop]
    paths-ignore:
      - 'README.md'
      - 'docs/**'
      - '*.md'
      - '.gitignore'
      - 'LICENSE'
      - '#GUIDE/**'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build & Test (Staging)
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push staging image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            assassincreed2k1/hanaya-shop:staging-latest
            assassincreed2k1/hanaya-shop:staging-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Run Tests (if you have tests)
        run: |
          echo "🧪 Running tests..."
          echo "📝 Add your test commands here"
          # docker run --rm assassincreed2k1/hanaya-shop:staging-${{ github.sha }} php artisan test

      - name: Security Scan (Optional)
        run: |
          echo "🔒 Security scan placeholder"
          echo "📝 Add security scanning here if needed"

  notify:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: success()
    steps:
      - name: Staging Build Success
        run: |
          echo "✅ Staging build completed successfully!"
          echo "🐳 Image: assassincreed2k1/hanaya-shop:staging-${{ github.sha }}"
          echo "📝 Ready for production deployment review"