name: 🌱 Staging Deployname: Staging Deploy



# Staging deployment for testing before productionon:

on:  push:

  push:    branches: [develop, staging]

    branches: [develop]  pull_request:

    paths-ignore:    branches: [main]

      - 'README.md'  workflow_dispatch:

      - 'docs/**'

      - '*.md'jobs:

      - '.gitignore'  build-and-test:

      - 'LICENSE'    runs-on: ubuntu-latest

      - '#GUIDE/**'    name: Build & Test (Staging)

    

  workflow_dispatch:    steps:

    inputs:      - name: Checkout code

      force_deploy:        uses: actions/checkout@v4

        description: 'Force staging deployment'

        required: false      - name: Set up Docker Buildx

        default: 'false'        uses: docker/setup-buildx-action@v3

        type: boolean

      - name: Login to DockerHub

jobs:        uses: docker/login-action@v3

  # 🌱 Staging Deployment        with:

  staging-deploy:          username: ${{ secrets.DOCKERHUB_USERNAME }}

    runs-on: ubuntu-latest          password: ${{ secrets.DOCKERHUB_TOKEN }}

    name: 🌱 Deploy to Staging Environment

    environment:      - name: Build and push staging image

      name: staging        uses: docker/build-push-action@v5

      url: http://staging.hanayashop.com        with:

          context: .

    steps:          push: true

      - name: Staging Deployment Info          tags: |

        run: |            assassincreed2k1/hanaya-shop:staging-latest

          echo "🌱 Starting Staging Deployment!"            assassincreed2k1/hanaya-shop:staging-${{ github.sha }}

          echo "Branch: ${{ github.ref }}"          cache-from: type=gha

          echo "Commit: ${{ github.sha }}"          cache-to: type=gha,mode=max

          echo "Repository: ${{ github.repository }}"

          echo "Purpose: Pre-production testing and validation"      - name: Run Tests (if you have tests)

        run: |

      - name: Checkout code          echo "🧪 Running tests..."

        uses: actions/checkout@v4          echo "📝 Add your test commands here"

          # docker run --rm assassincreed2k1/hanaya-shop:staging-${{ github.sha }} php artisan test

      - name: Set up Docker Buildx

        uses: docker/setup-buildx-action@v3      - name: Security Scan (Optional)

        run: |

      - name: Login to DockerHub          echo "🔒 Security scan placeholder"

        uses: docker/login-action@v3          echo "📝 Add security scanning here if needed"

        with:

          username: ${{ secrets.DOCKERHUB_USERNAME }}  notify:

          password: ${{ secrets.DOCKERHUB_TOKEN }}    runs-on: ubuntu-latest

    needs: build-and-test

      - name: Build and push staging Docker image    if: success()

        uses: docker/build-push-action@v5    steps:

        with:      - name: Staging Build Success

          context: .        run: |

          push: true          echo "✅ Staging build completed successfully!"

          tags: |          echo "🐳 Image: assassincreed2k1/hanaya-shop:staging-${{ github.sha }}"

            assassincreed2k1/hanaya-shop:staging          echo "📝 Ready for production deployment review"
            assassincreed2k1/hanaya-shop:staging-${{ github.sha }}
          labels: |
            git_sha=${{ github.sha }}
            build_date=${{ github.event.head_commit.timestamp }}
            version=staging
            environment=staging
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Deploy to Staging Server (if configured)
        run: |
          echo "🌱 Staging deployment completed!"
          echo "🐳 Docker image: assassincreed2k1/hanaya-shop:staging"
          echo "🔄 Ready for testing before production deployment"
          echo ""
          echo "📋 Next Steps:"
          echo "1. Test staging application thoroughly"
          echo "2. Verify all features work correctly"
          echo "3. Run integration tests"
          echo "4. When ready, merge to main for production deployment"
          echo ""
          echo "🌐 Staging URL: http://staging.hanayashop.com (when staging server configured)"

      - name: Staging Summary
        run: |
          echo "✅ Staging deployment completed successfully!"
          echo "🌱 Environment: Staging"
          echo "🐳 Docker image: assassincreed2k1/hanaya-shop:staging-${{ github.sha }}"
          echo "🎯 Purpose: Pre-production testing and validation"